Пробуем include
MrDave/StaticJinjaPlus pull request #14
Opened 2024-04-25 13:00 UTC by SGKespace

после  `python main.py ` include добавляет код из файла card.html  в index.html, но если запустить `python3 main.py -w` и внести изменения в card.html, то последний отрендерится, а  в index.html изменений не будет - вот что имелось ввиду[ Issues #11  ](https://github.com/MrDave/StaticJinjaPlus/issues/11)

2024-04-25 18:51 UTC, SGKespace commented
сделал развернутый ответ по проблеме с include в[ issues #11 ](https://github.com/MrDave/StaticJinjaPlus/issues/11)

2024-04-26 15:44 UTC, SGKespace commented
Правильно сделал include

2024-04-26 15:48 UTC, SGKespace commented
Исправил название файла

2024-04-26 19:00 UTC, pelid commented on templates_example/index.html
> +{% include "_card.html"  %}
Пример выглядит искусственно. И было здорово включать `_card.html` не в index.html, а в `_base.html`

2024-04-26 19:00 UTC, pelid commented on README.md
> +## Partials and ignored files
Пользователь вряд ли будет читать такой раздел в документации. Он им не интересен. Название раздел никак не перекликается с актуальными для пользователей проблемами.

2024-04-27 12:26 UTC, SGKespace commented
Красивое решение для переменных в include.

2024-04-27 18:41 UTC, SGKespace commented
Добавил меню в README.md и описание inclede  на русском

2024-05-04 19:19 UTC, pelid commented on README.md
> +Рассмотрим общие правила на примере include для файла _card.html  c вызовом из index.html.
Что-то сложно. Не понял что хотел сказать.

2024-05-04 19:24 UTC, pelid commented on README.md
> +Рассмотрим общие правила на примере include для файла _card.html  c вызовом из index.html.
Не хватает пояснений для тех, кто не знаком с `extends` и `include` -- что это такое?

2024-05-04 19:24 UTC, pelid commented on README.md
> +Рассмотрим общие правила на примере include для файла _card.html  c вызовом из index.html.
Хорошо бы в тексте каждое использование include, extend и прочих синтаксических конструкций выделить как вставки кода.

2024-05-04 19:24 UTC, pelid commented on README.md
> +- ```_card.html```:  имя файла имеет префикс «_» что объявляет его частичным, а значит при его изменении будут рендерится и все файлы в которых есть к нему обращение, а сам он не будет переносится в
Тройные бэктики используются для блочных вставок кода. Блочная вставка -- это отдельный абзац текста.

2024-05-04 19:24 UTC, pelid commented on README.md
> +- ```_card.html```:  имя файла имеет префикс «_» что объявляет его частичным, а значит при его изменении будут рендерится и все файлы в которых есть к нему обращение, а сам он не будет переносится в
частичный → вспомогательный

2024-05-04 19:26 UTC, pelid commented on README.md
> +- ```_card.html```:  имя файла имеет префикс «_» что объявляет его частичным, а значит при его изменении будут рендерится и все файлы в которых есть к нему обращение, а сам он не будет переносится в
Две мысли в одном предложении. Хорошо бы вынести объяснение термина частичный/вспомогательный в отдельное предложение.

2024-05-04 19:29 UTC, pelid commented on README.md
> +- Передача значений  переменных на примере page и  number.
Названия переменных хорошо бы выделить как вставки кода.

2024-05-04 19:29 UTC, pelid commented on README.md
> +- Пример строки в файле _card.html с переменными page и  number.
Пример строки в файле _card.html с переменными page и number. → Содержимое файла _card.html может выглядеть так:

2024-05-06 19:41 UTC, SGKespace commented
причесал Readme.md

2024-05-16 13:05 UTC, pelid requested changes

2024-05-16 13:05 UTC, pelid commented on README.md
> +  - [Шаблоны extends и include](#Шаблоны-extends-и-include)
Устаревшие разделы документации? Не нашёл таких в правках README. Перепроверь.

2024-05-16 13:05 UTC, pelid commented on README.md
> +- Фильтр `extends` используется когда шаблоны должны иметь одинаковую базовую структуру, одни и те же блоки, при этом определять для отдельных блоков различное содержимое. Это позволяет сформировать
одни и те же блоки → одну и ту же разбивку по блокам

2024-05-16 13:05 UTC, pelid commented on README.md
> +- Фильтр `extends` используется когда шаблоны должны иметь одинаковую базовую структуру, одни и те же блоки, при этом определять для отдельных блоков различное содержимое. Это позволяет сформировать
при этом определять для отдельных блоков различное содержимое → но с разным содержимым для этих блоков

2024-05-16 13:05 UTC, pelid commented on README.md
> +Пример кода c вызовом из `index.html`
О каком "вызове" речь?

2024-05-16 13:05 UTC, pelid commented on README.md
> +{% extends '_base.html' %}
Названия файлов принято указывать в начале сниппета с кодом. Вот так:

```html
<!-- index.html file -->
{% extends '_base.html' %}
```

2024-05-16 13:05 UTC, pelid commented on README.md
> +- Фильтр `include` позволяет добавить один шаблон в другой шаблон. Название подключаемого шаблона передается фильтру в качестве параметра.
`include` -- это не фильтр. Сверься с терминологией Jinja2.

2024-05-16 13:05 UTC, pelid commented on README.md
> +- Рассмотрим синтаксис на примере `include` для файла `_card.html`  c вызовом из `index.html`.
Это пояснение вообще ничего не поясняет. Оно лишь цитирует код.

Хорошее пояснение должно не цитировать код, а объяснять его предназначение -- что полезного он делает и чем оно полезно. Хорошее пояснение вообще не должно пользоваться терминологией из кода. Объясняй так, чтобы понял даже ребёнок, не знакомый с Jinja2.

Если объяснить просто не можешь, то лучше вообще ничего не писать. Кода будет достаточно.

2024-05-16 13:05 UTC, pelid commented on README.md
> +- `_card.html`:  имя файла имеет префикс «_» что объявляет его вспомогательным (подключаемым). При изменении вспомомгательного файла рендерится все файлы в которых есть к нему обращение.
опечатка "рендерится все файлы" → "рендерятся все файлы"

2024-05-16 13:05 UTC, pelid commented on README.md
> +- `_card.html`:  имя файла имеет префикс «_» что объявляет его вспомогательным (подключаемым). При изменении вспомомгательного файла рендерится все файлы в которых есть к нему обращение.
вспомомгательного -- опечатка

2024-05-16 14:59 UTC, SGKespace commented on README.md
> +- Фильтр `include` позволяет добавить один шаблон в другой шаблон. Название подключаемого шаблона передается фильтру в качестве параметра.
Можно ли поменять фильтр -> конструкция ?

2024-05-16 16:16 UTC, SGKespace commented on README.md
> +- Фильтр `include` позволяет добавить один шаблон в другой шаблон. Название подключаемого шаблона передается фильтру в качестве параметра.
ппоменял на вызов

2024-05-16 16:28 UTC, SGKespace commented
Причесал readme.md

2024-05-17 15:23 UTC, SGKespace commented
Немного сократил описание

2024-05-29 08:14 UTC, merged